### ISSUE TITLE
SEC Touch?

### ISSUE THREAD

**Issue by cservice000** [incub77/sevicontrol#1]
Hello , Nice work on this!!!!!

I have one question, you use this to tap the SEC-Touch ?

Best Regards  
Andrei

**Comment by incub77** [comment]
Hi Andrei,

I have a SEC-20. As far as i understand the whole system, you could just replace the SEC-20 by a SEC-Touch. Therefor this software should also work with SEC-Touch. It would be nice to get some logs of the messages send by SEC-Touch though, as the Touch seems to offer more ventilation modes.

Cheers,
incub
